version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: lms-backend
    ports:
      - "8000:8000"   # host port 8000 → container port 8000
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - lms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: lms-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge
